package apps.moreoffice.ext.biokee.bioplat.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IUruid", targetNamespace = "http://ws.bioplat.biokee.com/")
public interface IUruid {

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "bind", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.Bind")
	@ResponseWrapper(localName = "bindResponse", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.BindResponse")
	public String bind(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modify", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.Modify")
	@ResponseWrapper(localName = "modifyResponse", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.ModifyResponse")
	public String modify(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "register", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.Register")
	@ResponseWrapper(localName = "registerResponse", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.RegisterResponse")
	public String register(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "verify", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.Verify")
	@ResponseWrapper(localName = "verifyResponse", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.VerifyResponse")
	public String verify(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getToken", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.GetToken")
	@ResponseWrapper(localName = "getTokenResponse", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.GetTokenResponse")
	public String getToken(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getFingerInfo", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.GetFingerInfo")
	@ResponseWrapper(localName = "getFingerInfoResponse", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.GetFingerInfoResponse")
	public String getFingerInfo(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "nVerify", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.NVerify")
	@ResponseWrapper(localName = "nVerifyResponse", targetNamespace = "http://ws.bioplat.biokee.com/", className = "com.biokee.bioplat.demo.NVerifyResponse")
	public String nVerify(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

}
