package apps.moreoffice.ext.biokee.bioplat.demo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UruidImplService service = new UruidImplService();
 * IUruid portType = service.getUruidImplPort();
 * portType.bind(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UruidImplService", targetNamespace = "http://impl.ws.bioplat.biokee.com/", wsdlLocation = "http://service.uruid.com/service/IUruid?wsdl")
public class UruidImplService extends Service {

	private final static URL URUIDIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(apps.moreoffice.ext.biokee.bioplat.demo.UruidImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = apps.moreoffice.ext.biokee.bioplat.demo.UruidImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://service.uruid.com/service/IUruid?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://service.uruid.com/service/IUruid?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		URUIDIMPLSERVICE_WSDL_LOCATION = url;
	}

	public UruidImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UruidImplService() {
		super(URUIDIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://impl.ws.bioplat.biokee.com/", "UruidImplService"));
	}

	/**
	 * 
	 * @return returns IUruid
	 */
	@WebEndpoint(name = "UruidImplPort")
	public IUruid getUruidImplPort() {
		return super.getPort(new QName("http://impl.ws.bioplat.biokee.com/",
				"UruidImplPort"), IUruid.class);
	}

}
